name: BuildUbuntu

on:
  push:
    branches-ignore:
      - 'Windows-*'
  pull_request:
    branches-ignore:
      - 'Windows-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: BuildUbuntu
        run: |
          find . -name "*.sln" | while read solution; do
            dotnet build "$solution"
          done
